var d =["/Java/Introduction.mp4",
"/Java/How%20Java%20achieved%20platform%20independence.mp4",
"/Java/HelloWorld%20Example%20-%20(Manual%20Approach).mp4",
"/Java/Main%20method%20and%20its%20signature.mp4",
"/Java/HelloWorld%20Example%20-%20(Through%20Eclipse).mp4",
"/Java/Example%20-%20Addition%20of%20two%20numbers.mp4",
"/Java/Primitive%20Datatypes.mp4",
"/Java/Declarations%20and%20Literals.mp4",
"/Java/Example%20-%20Area%20of%20a%20Circle.mp4",
"/Java/Standard%20Streams%20and%20Reading%20data.mp4",
"/Java/Example%20-%20Values%20Swap.mp4",
"/Java/Operators%20Part%201%20-%20Arithmetic%20and%20Increment%20Operators.mp4",
"/Java/Operators%20Part%202%20-%20Relational%20and%20Logical%20Operators.mp4",
"/Java/Operators%20Part%203%20-%20Bitwise%20and%20Shift%20operators.mp4",
"/Java/Operators%20Part%204%20-%20Assignment%20and%20Ternary%20Operators.mp4",
"/Java/Expressions.mp4",
"/Java/Example%20-%20Need%20for%20Type%20Conversions.mp4",
"/Java/Type%20conversions%20heads%20up.mp4",
"/Java/Type%20Conversions.mp4",
"/Java/If%20Statement.mp4",
"/Java/Switch%20statement.mp4",
"/Java/While%20statement.mp4",
"/Java/Example%20-%20Prime%20Number.mp4",
"/Java/Other%20looping%20structures%20along%20with%20break%20and%20continue.mp4",
"/Java/Revised%20Example%20-%20Prime%20Number.mp4",
"/Java/Getting%20started%20with%20functions%20with%20simple%20example.mp4",
"/Java/NcR%20example%20with%20and%20with%20out%20functions.mp4",
"/Java/Arrays.mp4",
"/Java/Example%20-%20Array%20read%20and%20print.mp4",
"/Java/Example%20-%20Finding%20biggest%20in%20the%20array.mp4",
"/Java/Call%20by%20value%20and%20call%20by%20reference.mp4",
"/Java/Introduction%20to%20classes.mp4",
"/Java/Encapsulation%20and%20DataHiding.mp4",
"/Java/What%20is%20Object?.mp4",
"/Java/Introduction%20to%20Overloading.mp4",
"/Java/Need%20for%20Overloading.mp4",
"/Java/Variable%20arguments%20along%20with%20overloading.mp4",
"/Java/Static%20vs%20Non%20Static%20members.mp4",
"/Java/Initializers.mp4",
"/Java/Constructors%20and%20Constructor%20overloading.mp4",
"/Java/this%20keyword.mp4",
"/Java/Code%20reuse%20through%20Inheritance.mp4",
"/Java/Overriding%20and%20Dynamic%20binding.mp4",
"/Java/Super%20keyword%20and%20constructors%20in%20inheritance.mp4",
"/Java/Code%20Generalization%20and%20Introduction%20to%20Object%20class.mp4",
"/Java/Introduction%20to%20abstract%20classes.mp4",
"/Java/Final%20Modifier.mp4",
"/Java/Technical%20points%20related%20to%20abstract%20classes.mp4",
"/Java/Static%20Binding%20vs%20Dynamic%20Binding.mp4",
"/Java/Template%20method%20pattern.mp4",
"/Java/Introduction%20to%20interface.mp4",
"/Java/Implementing%20multiple%20interfaces.mp4",
"/Java/Role%20of%20Interfaces%20in%20Loosely%20Coupled%20Code.mp4",
"/Java/Interfaces%20for%20Pluggable%20Code.mp4",
"/Java/String%20and%20immutability.mp4",
"/Java/String%20comparison.mp4",
"/Java/Simple%20text%20search.mp4",
"/Java/StringBuilder.mp4",
"/Java/Introduction%20to%20Packages.mp4",
"/Java/Static%20imports.mp4",
"/Java/Access%20modifiers.mp4",
"/Java/Introduction%20to%20exception%20handling.mp4",
"/Java/Defining%20custom%20exceptions.mp4",
"/Java/Checked%20and%20unchecked%20exceptions.mp4",
"/Java/Example.mp4",
"/Java/Finally%20block.mp4",
"/Java/Basic%20File%20IO.mp4",
"/Java/Copy%20Utility.mp4",
"/Java/Copy%20utility%20refined.mp4",
"/Java/BufferedIO.mp4",
"/Java/Generic%20Classes%20Example.mp4",
"/Java/Generic%20Methods.mp4",
"/Java/Collections%20Overview.mp4",
"/Java/Working%20with%20Map.mp4",
"/Java/Remove%20duplicates%20example%20and%20Iterator.mp4",
"/Java/Custom%20Types%20with%20Hashed%20Collections.mp4",
"/Java/Comparable%20and%20Comparator.mp4",
"/Java/Introduction%20to%20Nested%20Classes.mp4",
"/Java/Inner%20Class%20Usage%20with%20Example.mp4",
"/Java/Local%20and%20Anonymous%20classes.mp4",
"/Java/Introduction%20to%20Lambdas.mp4",
"/Java/Lambda%20Example.mp4",
"/Java/Lambda%20for%20Comparator.mp4",
"/Java/Method%20References%20in%20Lambda.mp4",
"/Java/Introduction%20to%20JDBC.mp4",
"/Java/First%20example%20using%20JDBC.mp4",
"/Java/Revised%20Example%20using%20Maven.mp4",
"/Java/Different%20execute%20methods%20of%20the%20Statement.mp4",
"/Java/SQL%20Injection%20Attacks%20and%20PreparedStatements.mp4",
"/Java/Manually%20controlling%20the%20transactions.mp4",
"/Java/Calling%20Stored%20Procedures.mp4",
"/Java/DataSource%20and%20Connection%20Pooling.mp4",
"/Java/Introduction%20to%20Object%20Relational%20Mapping%20(ORM).mp4",
"/Java/Introduction%20and%20Basic%20Application%20Setup.mp4",
"/Java/Persistence%20Layer%20-%20Part%201.mp4",
"/Java/Persistence%20Layer%20-%20Part%202.mp4",
"/Java/Service%20Layer.mp4",
"/Java/API%20Layer%20-%20Part%20-%201.mp4",
"/Java/API%20Layer%20-%20Part%20-%202.mp4",
"/Java/View%20Layer%20-%20Part%20-%201.mp4",
"/Java/View%20Layer%20-%20Part%20-%202.mp4",
"/Java/Externalizing%20the%20properties.mp4"];

var d1 =["Introduction",
"How Java achieved platform independence?",
"HelloWorld Example - (Manual Approach)",
"Main method and its signature",
"HelloWorld Example - (Through Eclipse)",
"Example - Addition of two numbers",
"Primitive Datatypes",
"Declarations and Literals",
"Example - Area of a Circle",
"Standard Streams and Reading data",
"Example - Values Swap",
"Operators Part 1 - Arithmetic and Increment Operators",
"Operators Part 2 - Relational and Logical Operators",
"Operators Part 3 - Bitwise and Shift operators",
"Operators Part 4 - Assignment and Ternary Operators",
"Expressions",
"Example - Need for Type Conversions",
"Type conversions heads up",
"Type Conversions",
"If Statement",
"Switch statement",
"While statement",
"Example - Prime Number",
"Other looping structures along with break and continue",
"Revised Example - Prime Number",
"Getting started with functions with simple example",
"NcR example with and with out functions",
"Arrays",
"Example - Array read and print",
"Example - Finding biggest in the array",
"Call by value and call by reference",
"Introduction to classes",
"Encapsulation and DataHiding",
"What is Object?",
"Introduction to Overloading",
"Need for Overloading",
"Variable arguments along with overloading",
"Static vs Non Static members",
"Initializers",
"Constructors and Constructor overloading",
"this keyword",
"Code reuse through Inheritance",
"Overriding and Dynamic binding",
"Super keyword and constructors in inheritance",
"Code Generalization and Introduction to Object class",
"Introduction to abstract classes",
"Final Modifier",
"Technical points related to abstract classes",
"Static Binding vs Dynamic Binding",
"Template method pattern",
"Introduction to interface",
"Implementing multiple interfaces",
"Role of Interfaces in Loosely Coupled Code",
"Interfaces for Pluggable Code",
"String and immutability",
"String comparison",
"Simple text search",
"StringBuilder",
"Introduction to Packages",
"Static imports",
"Access modifiers",
"Introduction to exception handling",
"Defining custom exceptions",
"Checked and unchecked exceptions",
"Example",
"Finally block",
"Basic File IO",
"Copy Utility",
"Copy utility refined",
"BufferedIO",
"Generic Classes Example",
"Generic Methods",
"Collections Overview",
"Working with Map",
"Remove duplicates example and Iterator",
"Custom Types with Hashed Collections",
"Comparable and Comparator",
"Introduction to Nested Classes",
"Inner Class Usage with Example",
"Local and Anonymous classes",
"Introduction to Lambdas",
"Lambda Example",
"Lambda for Comparator",
"Method References in Lambda",
"Introduction to JDBC",
"First example using JDBC",
"Revised Example using Maven",
"Different execute methods of the Statement",
"SQL Injection Attacks and PreparedStatements",
"Manually controlling the transactions",
"Calling Stored Procedures",
"DataSource and Connection Pooling",
"Introduction to Object Relational Mapping (ORM)",
"Introduction and Basic Application Setup",
"Persistence Layer - Part 1",
"Persistence Layer - Part 2",
"Service Layer",
"API Layer - Part - 1",
"API Layer - Part - 2",
"View Layer - Part - 1",
"View Layer - Part - 2",
"Externalizing the properties"]

var j=0;
const html = d.map((img, i) =>{
    var lv = d[i];
    var lb = lv;
    // var lv = btoa(lv);
    // var ls = `/${lv}.mp4`
    return `
            <div class="col-sm-6">
                <div class="card text-white bg-dark mb-3">
                  <div class="card-body">
                    <h5 class="card-title">${d1[i]}</h5>
                    <p class="card-text">
                    Learn ${d1[i]}
                    </p>
                    <a href="java.html?link=${lv}" class="btn btn-light">Watch Now</a>
                  </div>
                </div>
              </div>`;
    j++;
}).join('');
document.querySelector("#row").insertAdjacentHTML("afterbegin", html);

const params = new URLSearchParams(document.location.search);
var link = params.get("link");
var temp = link;
temp=temp.replace(".mp4", "");
document.title = `HealCourse | ${temp}`;
document.getElementById("watch").innerHTML = `Watching ${temp}`

var key= "aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3R1dGVkdWRlNjk0";
link = `${atob(key)}${link}`
var player = new Playerjs({id:"player", autoplay:"1", file:link});
