var d =["/MERN%20Stack/Introduction%20to%20the%20course.mp4",
"/MERN%20Stack/How%20internet%20works.mp4",
"/MERN%20Stack/What%20is%20web%20development.mp4",
"/MERN%20Stack/Your%20first%20webpage.mp4",
"/MERN%20Stack/The%20structure%20of%20a%20Webpage.mp4",
"/MERN%20Stack/Creating%20a%20full%20webpage.mp4",
"/MERN%20Stack/Header%20tags.mp4",
"/MERN%20Stack/Paragraph%20tags.mp4",
"/MERN%20Stack/Formatting%20tags.mp4",
"/MERN%20Stack/Unordered%20list.mp4",
"/MERN%20Stack/Ordered%20list.mp4",
"/MERN%20Stack/Image%20tags.mp4",
"/MERN%20Stack/Forms%20in%20HTML.mp4",
"/MERN%20Stack/Tables.mp4",
"/MERN%20Stack/Links.mp4",
"/MERN%20Stack/HTML%20entities.mp4",
"/MERN%20Stack/iFrame.mp4",
"/MERN%20Stack/PROJECT-%20Putting%20it%20all%20together.mp4",
"/MERN%20Stack/What%20is%20CSS.mp4",
"/MERN%20Stack/Inline%20CSS.mp4",
"/MERN%20Stack/Internal%20CSS.mp4",
"/MERN%20Stack/Class%20and%20id.mp4",
"/MERN%20Stack/Div.mp4",
"/MERN%20Stack/Color.mp4",
"/MERN%20Stack/Floating.mp4",
"/MERN%20Stack/Positions.mp4",
"/MERN%20Stack/Margins.mp4",
"/MERN%20Stack/Padding.mp4",
"/MERN%20Stack/Borders.mp4",
"/MERN%20Stack/Font%20style.mp4",
"/MERN%20Stack/Styling%20text.mp4",
"/MERN%20Stack/Aligning%20text.mp4",
"/MERN%20Stack/Styling%20links.mp4",
"/MERN%20Stack/FlexBox%20in%20CSS.mp4",
"/MERN%20Stack/Inline%20javascript.mp4",
"/MERN%20Stack/Internal%20javascript.mp4",
"/MERN%20Stack/Accessing%20elements.mp4",
"/MERN%20Stack/Onclick%20event.mp4",
"/MERN%20Stack/Changing%20Website%20content.mp4",
"/MERN%20Stack/Manupulating%20styles%20with%20javascript.mp4",
"/MERN%20Stack/Disappearing%20circles.mp4",
"/MERN%20Stack/Variables.mp4",
"/MERN%20Stack/Array.mp4",
"/MERN%20Stack/If%20statement.mp4",
"/MERN%20Stack/Random%20number%20guessing%20game.mp4",
"/MERN%20Stack/For%20loop.mp4",
"/MERN%20Stack/While%20loop.mp4",
"/MERN%20Stack/PROJECT-Reaction%20tester%20project.mp4",
"/MERN%20Stack/External%20javascript.mp4",
"/MERN%20Stack/DOM%20intro.mp4",
"/MERN%20Stack/Naming%20conventions.mp4",
"/MERN%20Stack/String%20concat.mp4",
"/MERN%20Stack/Length%20property%20in%20strings.mp4",
"/MERN%20Stack/Slicing.mp4",
"/MERN%20Stack/Changing%20Case%20of%20string.mp4",
"/MERN%20Stack/Operators%20in%20js.mp4",
"/MERN%20Stack/Functions.mp4",
"/MERN%20Stack/Objects.mp4",
"/MERN%20Stack/How%20to%20add%20event%20listener%20in%20js.mp4",
"/MERN%20Stack/What%20is%20jQuery.mp4",
"/MERN%20Stack/Including%20jQuery%20on%20our%20webpage.mp4",
"/MERN%20Stack/Detecting%20a%20click.mp4",
"/MERN%20Stack/Changing%20website%20content%20using%20jQuery.mp4",
"/MERN%20Stack/Changing%20website%20styles.mp4",
"/MERN%20Stack/Fading%20content.mp4",
"/MERN%20Stack/Regular%20expression.mp4",
"/MERN%20Stack/PROJECT-Form%20Validation.mp4",
"/MERN%20Stack/Intro%20to%20jquery%20Ui%20Plugin.mp4",
"/MERN%20Stack/Droppable.mp4",
"/MERN%20Stack/Jqui%20widget.mp4",
"/MERN%20Stack/Intro%20to%20Bootstrap.mp4",
"/MERN%20Stack/Your%20first%20bootstrap%20site.mp4",
"/MERN%20Stack/Grid.mp4",
"/MERN%20Stack/Card%20in%20bootstrap.mp4",
"/MERN%20Stack/Tables%20and%20Form.mp4",
"/MERN%20Stack/Modals,popover%20and%20tooltips.mp4",
"/MERN%20Stack/Scrollspy.mp4",
"/MERN%20Stack/PROJECT-App%20landing%20project.mp4",
"/MERN%20Stack/Themes%20in%20bootstrap.mp4",
"/MERN%20Stack/Setting%20up%20the%20folder%20structure.mp4",
"/MERN%20Stack/Responsive%20grid%20system.mp4",
"/MERN%20Stack/Header%20section%20-%20Part-1.mp4",
"/MERN%20Stack/Header%20section%20-%20Part-2.mp4",
"/MERN%20Stack/Header%20section%20-%20Part-3.mp4",
"/MERN%20Stack/Feature%20section%20-%20Part-1.mp4",
"/MERN%20Stack/Feature%20section%20-%20Part-2.mp4",
"/MERN%20Stack/Creating%20Favorite%20meal%20section%20-%20Part-1.mp4",
"/MERN%20Stack/Creating%20Favorite%20meal%20section%20-%20Part-2.mp4",
"/MERN%20Stack/Creating%20how%20it%20works%20section%20-%20Part-1.mp4",
"/MERN%20Stack/Creating%20how%20it%20works%20section%20-%20Part-2.mp4",
"/MERN%20Stack/Creating%20the%20city%20section%20-%20Part-1.mp4",
"/MERN%20Stack/Creating%20the%20city%20section%20-%20Part-2.mp4",
"/MERN%20Stack/Creating%20Customer%20testimonial%20section%20-%20Part-1.mp4",
"/MERN%20Stack/Creating%20Customer%20testimonial%20section%20-%20Part-2.mp4",
"/MERN%20Stack/Creating%20Sign%20up%20section%20-%20Part-1.mp4",
"/MERN%20Stack/Creating%20Sign%20up%20section%20-%20Part-2.mp4",
"/MERN%20Stack/Creating%20the%20contact%20form%20section%20-%20Part-1.mp4",
"/MERN%20Stack/Creating%20the%20contact%20form%20section%20-%20Part-2.mp4",
"/MERN%20Stack/Creating%20the%20footer%20section%20-%20Part-1.mp4",
"/MERN%20Stack/Creating%20the%20footer%20section%20-%20Part-2.mp4",
"/MERN%20Stack/Making%20webpage%20responsive%20-%20Part-1.mp4",
"/MERN%20Stack/Making%20webpage%20responsive%20-%20Part-2.mp4",
"/MERN%20Stack/Including%20jquery.mp4",
"/MERN%20Stack/Scrolling%20effect.mp4",
"/MERN%20Stack/Adding%20animations.mp4",
"/MERN%20Stack/Backend.mp4",
"/MERN%20Stack/Nodejs.mp4",
"/MERN%20Stack/REPL.mp4",
"/MERN%20Stack/Native%20modules.mp4",
"/MERN%20Stack/Modules%20in%20nodejs.mp4",
"/MERN%20Stack/Express%20with%20Nodejs.mp4",
"/MERN%20Stack/Express%20framework.mp4",
"/MERN%20Stack/Creating%20a%20server%20using%20express.mp4",
"/MERN%20Stack/Request%20and%20response%20using%20express.mp4",
"/MERN%20Stack/Routes.mp4",
"/MERN%20Stack/Sending%20html%20file%20as%20a%20response.mp4",
"/MERN%20Stack/Post%20request%20in%20express.mp4",
"/MERN%20Stack/API.mp4",
"/MERN%20Stack/Authentication%20and%20JSON.mp4",
"/MERN%20Stack/Weather%20app.mp4",
"/MERN%20Stack/Git.mp4",
"/MERN%20Stack/Version%20control%20using%20git.mp4",
"/MERN%20Stack/Github%20and%20remote%20repositories.mp4",
"/MERN%20Stack/Clonning.mp4",
"/MERN%20Stack/Forking%20and%20pulling%20request.mp4",
"/MERN%20Stack/EJS.mp4",
"/MERN%20Stack/Creating%20Ejs%20template.mp4",
"/MERN%20Stack/Creating%20a%20Todo%20list%20project%20Part-1.mp4",
"/MERN%20Stack/Creating%20a%20Todo%20list%20Part-2.mp4",
"/MERN%20Stack/Layouts%20In%20ejs.mp4",
"/MERN%20Stack/Creating%20our%20own%20modules.mp4",
"/MERN%20Stack/EJS%20Mongodb%20Database.mp4",
"/MERN%20Stack/What%20is%20database.mp4",
"/MERN%20Stack/Installing%20mongodb.mp4",
"/MERN%20Stack/Create%20In%20CRUD.mp4",
"/MERN%20Stack/Read%20In%20CRUD.mp4",
"/MERN%20Stack/Update%20and%20Delete%20In%20CRUD.mp4",
"/MERN%20Stack/Relationship%20In%20mongodb.mp4",
"/MERN%20Stack/Mongoose.mp4",
"/MERN%20Stack/Retriving%20Data%20from%20Database.mp4",
"/MERN%20Stack/Data%20Validation.mp4",
"/MERN%20Stack/Delete%20and%20Update.mp4",
"/MERN%20Stack/Connecting%20documents.mp4",
"/MERN%20Stack/Storing%20list%20items%20permanently%20PART-1.mp4",
"/MERN%20Stack/Storing%20list%20item%20permanently%20PART-2.mp4",
"/MERN%20Stack/Deleting%20a%20task%20from%20todo%20list.mp4",
"/MERN%20Stack/what%20REST.mp4",
"/MERN%20Stack/Setting%20Up%20Robo%203T.mp4",
"/MERN%20Stack/Get%20All%20Articles.mp4",
"/MERN%20Stack/Post%20a%20new%20article.mp4",
"/MERN%20Stack/Delete%20Request.mp4",
"/MERN%20Stack/Making%20a%20specific%20get%20request.mp4",
"/MERN%20Stack/Put%20operation%20on%20a%20specific%20record.mp4",
"/MERN%20Stack/Patch%20request.mp4",
"/MERN%20Stack/Deleteing%20a%20specific%20record.mp4",
"/MERN%20Stack/Intro%20to%20Authentication%20and%20security.mp4",
"/MERN%20Stack/Setting%20Up%20folder%20structure.mp4",
"/MERN%20Stack/Register%20and%20login.mp4",
"/MERN%20Stack/Encryption.mp4",
"/MERN%20Stack/Cookies%20and%20Session.mp4",
"/MERN%20Stack/Intro%20to%20Reactjs.mp4",
"/MERN%20Stack/Code%20sandbox.mp4",
"/MERN%20Stack/JSX%20and%20babel.mp4",
"/MERN%20Stack/JSX%20practice.mp4",
"/MERN%20Stack/Javascript%20expression%20in%20JSX%20practice.mp4",
"/MERN%20Stack/Javascript%20expression%20in%20jsx.mp4",
"/MERN%20Stack/JSX%20styling%20React%20elements.mp4",
"/MERN%20Stack/Inline%20style%20for%20React%20elements.mp4",
"/MERN%20Stack/React%20styling%20practice.mp4",
"/MERN%20Stack/React%20Components.mp4",
"/MERN%20Stack/React%20Component%20Practice.mp4",
"/MERN%20Stack/Import%20and%20export.mp4",
"/MERN%20Stack/Export%20and%20import%20Practice.mp4",
"/MERN%20Stack/Keeper%20app%20Project%20Part-1.mp4",
"/MERN%20Stack/Props%20in%20reactjs.mp4",
"/MERN%20Stack/Adding%20React%20js%20developer%20tools.mp4",
"/MERN%20Stack/Mapping%20Data%20to%20components.mp4",
"/MERN%20Stack/Map%20function%20Practice%20challenge.mp4",
"/MERN%20Stack/Map%20reduce%20and%20filter%20function%20In%20js%20ES6.mp4",
"/MERN%20Stack/Arrow%20function%20in%20ES6.mp4",
"/MERN%20Stack/Keeper%20App%20project%20Part-2.mp4",
"/MERN%20Stack/React%20Condiitional%20rendering.mp4",
"/MERN%20Stack/ReactJs%20states.mp4",
"/MERN%20Stack/React%20Hooks%20UseState.mp4",
"/MERN%20Stack/Hooks%20use%20state%20practice.mp4",
"/MERN%20Stack/Destructure%20Concept%20in%20ES6.mp4",
"/MERN%20Stack/Handling%20events%20in%20React.mp4",
"/MERN%20Stack/Form%20Events.mp4",
"/MERN%20Stack/Class%20component%20Vs%20Hooks.mp4",
"/MERN%20Stack/Handling%20multiple%20states%20in%20react%20js%20app.mp4",
"/MERN%20Stack/Spread%20operator.mp4",
"/MERN%20Stack/Component%20tree%20structure.mp4",
"/MERN%20Stack/Keeper%20app%20project-3.mp4",
"/MERN%20Stack/Material%20UI.mp4"];

var d1 =["Introduction to the course",
"How internet works",
"What is web development",
"Your first webpage",
"The structure of a Webpage",
"Creating a full webpage",
"Header tags",
"Paragraph tags",
"Formatting tags",
"Unordered list",
"Ordered list",
"Image tags",
"Forms in HTML",
"Tables",
"Links",
"HTML entities",
"iFrame",
"PROJECT- Putting it all together",
"What is CSS",
"Inline CSS",
"Internal CSS",
"Class and id",
"Div",
"Color",
"Floating",
"Positions",
"Margins",
"Padding",
"Borders",
"Font style",
"Styling text",
"Aligning text",
"Styling links",
"FlexBox in CSS",
"Inline javascript",
"Internal javascript",
"Accessing elements",
"Onclick event",
"Changing Website content",
"Manupulating styles with javascript",
"Disappearing circles",
"Variables",
"Array",
"If statement",
"Random number guessing game",
"For loop",
"While loop",
"PROJECT-Reaction tester project",
"External javascript",
"DOM intro",
"Naming conventions",
"String concat",
"Length property in strings",
"Slicing",
"Changing Case of string",
"Operators in js",
"Functions",
"Objects",
"How to add event listener in js",
"What is jQuery",
"Including jQuery on our webpage",
"Detecting a click",
"Changing website content using jQuery",
"Changing website styles",
"Fading content",
"Regular expression",
"PROJECT-Form Validation",
"Intro to jquery Ui Plugin",
"Droppable",
"Jqui widget",
"Intro to Bootstrap",
"Your first bootstrap site",
"Grid",
"Card in bootstrap",
"Tables and Form",
"Modals,popover and tooltips",
"Scrollspy",
"PROJECT-App landing project",
"Themes in bootstrap",
"Setting up the folder structure",
"Responsive grid system",
"Header section - Part-1",
"Header section - Part-2",
"Header section - Part-3",
"Feature section - Part-1",
"Feature section - Part-2",
"Creating Favorite meal section - Part-1",
"Creating Favorite meal section - Part-2",
"Creating how it works section - Part-1",
"Creating how it works section - Part-2",
"Creating the city section - Part-1",
"Creating the city section - Part-2",
"Creating Customer testimonial section - Part-1",
"Creating Customer testimonial section - Part-2",
"Creating Sign up section - Part-1",
"Creating Sign up section - Part-2",
"Creating the contact form section - Part-1",
"Creating the contact form section - Part-2",
"Creating the footer section - Part-1",
"Creating the footer section - Part-2",
"Making webpage responsive - Part-1",
"Making webpage responsive - Part-2",
"Including jquery",
"Scrolling effect",
"Adding animations",
"Backend",
"Nodejs",
"REPL",
"Native modules",
"Modules in nodejs",
"Express with Nodejs",
"Express framework",
"Creating a server using express",
"Request and response using express",
"Routes",
"Sending html file as a response",
"Post request in express",
"API",
"Authentication and JSON",
"Weather app",
"Git",
"Version control using git",
"Github and remote repositories",
"Clonning",
"Forking and pulling request",
"EJS",
"Creating Ejs template",
"Creating a Todo list project Part-1",
"Creating a Todo list Part-2",
"Layouts In ejs",
"Creating our own modules",
"EJS Mongodb Database",
"What is database",
"Installing mongodb",
"Create In CRUD",
"Read In CRUD",
"Update and Delete In CRUD",
"Relationship In mongodb",
"Mongoose",
"Retriving Data from Database",
"Data Validation",
"Delete and Update",
"Connecting documents",
"Storing list items permanently PART-1",
"Storing list item permanently PART-2",
"Deleting a task from todo list",
"what REST",
"Setting Up Robo 3T",
"Get All Articles",
"Post a new article",
"Delete Request",
"Making a specific get request",
"Put operation on a specific record",
"Patch request",
"Deleteing a specific record",
"Intro to Authentication and security",
"Setting Up folder structure",
"Register and login",
"Encryption",
"Cookies and Session",
"Intro to Reactjs",
"Code sandbox",
"JSX and babel",
"JSX practice",
"Javascript expression in JSX practice",
"Javascript expression in jsx",
"JSX styling React elements",
"Inline style for React elements",
"React styling practice",
"React Components",
"React Component Practice",
"Import and export",
"Export and import Practice",
"Keeper app Project Part-1",
"Props in reactjs",
"Adding React js developer tools",
"Mapping Data to components",
"Map function Practice challenge",
"Map reduce and filter function In js ES6",
"Arrow function in ES6",
"Keeper App project Part-2",
"React Condiitional rendering",
"ReactJs states",
"React Hooks UseState",
"Hooks use state practice",
"Destructure Concept in ES6",
"Handling events in React",
"Form Events",
"Class component Vs Hooks",
"Handling multiple states in react js app",
"Spread operator",
"Component tree structure",
"Keeper app project-3",
"Material UI"]

var j=0;
const html = d.map((img, i) =>{
    var lv = d[i];
    var lb = lv;
    // var lv = btoa(lv);
    // var ls = `/${lv}.mp4`
    return `
            <div class="col-sm-6">
                <div class="card text-white bg-dark mb-3">
                  <div class="card-body">
                    <h5 class="card-title">${d1[i]}</h5>
                    <p class="card-text">
                    Learn ${d1[i]}
                    </p>
                    <a href="mernstack.html?link=${lv}" class="btn btn-light">Watch Now</a>
                  </div>
                </div>
              </div>`;
    j++;
}).join('');
document.querySelector("#row").insertAdjacentHTML("afterbegin", html);

const params = new URLSearchParams(document.location.search);
var link = params.get("link");
var temp = link;
temp=temp.replace(".mp4", "");
document.title = `HealCourse | ${temp}`;
document.getElementById("watch").innerHTML = `Watching ${temp}`
var key= "aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL3R1dGVkdWRlNjk0";
link = `${atob(key)}${link}`
var player = new Playerjs({id:"player", autoplay:"1", file:link});
